//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4338
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISRPO
    {
        public int ID { get; set; }
        public string Наименование_услуги { get; set; }
        public string Вид_услуги { get; set; }
        public string Код_услуги { get; set; }
        public string Стоимость { get; set; }
    }
}
